services:
  longbridge:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - air_config:/root/.air
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  air_config: